### ISSUE TITLE
Merge multiple utilities into one

### ISSUE THREAD

**Issue by ayulockin** [thecodefoundation/Vison-WoC-Backend#1]
Under `indexer/postgresqlDB` we have two separate scripts named `createTable.py` and `addColumns.py`. They respectively create the SQL table and add columns to the table. The columns are names of the classes on which our YOLOv3 is trained. 

Merge them into a single script. Also make sure to update the README.md for the indexer accordingly.

**Comment by spacemonkey1101** [comment]
can I work on this?

**Comment by ayulockin** [comment]
Yes please go ahead. @spacemonkey1101
