### ISSUE TITLE
Change the database from SQLite to postgreSQL

### ISSUE THREAD

**Issue by sunitasen** [thecodefoundation/Vison-WoC-Backend#2]
1. Create a database named `vison.db` 
2. A table `urls` with column names `urlId(text)` and `rank(integer)` .
3. Choose an appropriate connector, you can look for the `psycopg2` module.

**Comment by Nerocodes** [comment]
Can I work on this?

**Comment by ayulockin** [comment]
Sure go ahead. :) @Nerocodes

**Comment by Nerocodes** [comment]
Please, I'll like to clarify a few things.
- Noticed there's already a Postgres database connection, I'm I to create a new one in a different folder or use the existing and add the column stated above?

**Comment by ayulockin** [comment]
Surely,

The requirement is have a Postgres database for the crawler. The Postres folder that you found is for the indexer. Create a new one in a different folder and proceed accordingly. 

I hope this helps. :D

**Comment by sunitasen** [comment]
Hey @Nerocodes ! It's been a long time since we have not heard from you! 😞 
I am unassigning you this issue as there is already a PR ready.
Feel free to contribute to other issues!

**Comment by Nerocodes** [comment]
Apologies... I couldn't get around to it. Thank you for the opportunity
